package com.github.brickwall2900;

import java.io.*;
import java.net.URL;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Optional;
import java.util.UUID;

public class IOUtilities {
    public static final int DOWNLOAD_ATTEMPTS = 10;
    private IOUtilities() { throw new UnsupportedOperationException("No IOUtilities for you!"); }

    /**
     * Copies from {@code src} to the target {@code dest}
     * @param src file source
     * @param dest file destination
     * @throws IOException on file read/write failure
     */
    public static void copySingleFile(File src, File dest) throws IOException {
        try (BufferedInputStream srcStream = new BufferedInputStream(new FileInputStream(src));
             BufferedOutputStream destStream = new BufferedOutputStream(new FileOutputStream(dest))) {
            srcStream.transferTo(destStream);
        }
    }

    /**
     * Downloads a file from the internet given {@code url} and writes it onto file {@code dest}
     * @param url website to download a file
     * @param dest file destination
     * @throws IOException on URL connect or file write failure
     */
    public static void downloadToFile(URL url, File dest) throws IOException {
        try (BufferedInputStream srcStream = new BufferedInputStream(url.openStream());
             BufferedOutputStream destStream = new BufferedOutputStream(new FileOutputStream(dest))) {
            srcStream.transferTo(destStream);
        }
    }

    /**
     * Downloads a file from the internet to a String
     * @param url website to download a file
     * @return the downloaded contents of a URL
     * @throws IOException on URL connect failure
     */
    public static String downloadToString(URL url) throws IOException {
        try (BufferedInputStream srcStream = new BufferedInputStream(url.openStream())) {
            return new String(srcStream.readAllBytes());
        }
    }

    /**
     * Reads the whole files contents into a String
     * @param file input file
     * @return the file contents
     * @throws IOException on file read failure
     */
    public static String readFileToString(File file) throws IOException {
        return Files.readString(file.toPath());
    }

    /**
     * Checks if the file's contents isn't empty
     * @param file input file
     * @return {@code true} if the file isn't empty, otherwise {@code false}
     * @throws IOException on file read failure
     */
    public static boolean isFileNotEmpty(File file) throws IOException {
        try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(file))) {
            return bis.read() != -1;
        }
    }

    /**
     * Check the file's integrity based on the given parameters
     * @param file input file to be verified
     * @param size correct file size
     * @param sha1 correct SHA-1 of file
     * @return {@code true} if the file matches the parameters, {@code false} otherwise
     * @throws RuntimeException on error while checking
     */
    public static boolean checkFileIntegrity(File file, long size, String sha1) {
        try {
            return file != null && file.exists() && file.length() == size && sha1.equalsIgnoreCase(bytesToHex(getHash(file, SHA1_ALGORITHM)));
        } catch (NoSuchAlgorithmException | IOException e) {
            throw new RuntimeException("Error checking the file integrity of " + file + "!", e);
        }
    }

    /**
     * Checks the file's integrity based on the given parameters excluding size
     * @param file input file to be verified
     * @param sha1 correct SHA-1 of file
     * @return {@code true} if the file matches the parameters, {@code false} otherwise
     * @throws RuntimeException on error while checking
     */
    public static boolean checkFileIntegrity(File file, String sha1) {
        try {
            return file != null && file.exists() && sha1.equalsIgnoreCase(bytesToHex(getHash(file, SHA1_ALGORITHM)));
        } catch (NoSuchAlgorithmException | IOException e) {
            throw new RuntimeException("Error checking the file integrity of " + file + "!", e);
        }
    }


    public static final String SHA1_ALGORITHM = "SHA-1";
    public static final int BUFFER_SIZE = 8192;

    /**
     * Gets the hash of the file generated by the algorithm
     * @param algorithm algorithm name
     * @return hash of the file
     * @throws NoSuchAlgorithmException if the algorithm doesn't exist
     * @throws IOException on file read failure
     */
    public static byte[] getHash(File file, String algorithm) throws NoSuchAlgorithmException, IOException {
        MessageDigest digest = MessageDigest.getInstance(algorithm);
        byte[] buffer = new byte[BUFFER_SIZE];
        try (BufferedInputStream input = new BufferedInputStream(new FileInputStream(file))) {
            int len = input.read(buffer);

            while (len != -1) {
                digest.update(buffer, 0, len);
                len = input.read(buffer);
            }

            return digest.digest();
        }
    }

    /**
     * Takes a byte array and turns it into the hexadecimal representation of it.
     * @param bytes byte array
     * @return hexadecimal representation of the byte array
     */
    public static String bytesToHex(byte[] bytes) {
        StringBuilder hexString = new StringBuilder(2 * bytes.length);
        for (byte b : bytes) {
            String hex = Integer.toHexString(0xff & b);
            if (hex.length() == 1) {
                hexString.append('0');
            }
            hexString.append(hex);
        }
        return hexString.toString();
    }

    /**
     * Queries the currently running Java version
     * @return the java version
     */
    public static int getJavaVersion() {
        String version = System.getProperty("java.version");
        if(version.startsWith("1.")) {
            version = version.substring(2, 3);
        } else {
            int dot = version.indexOf(".");
            if(dot != -1) { version = version.substring(0, dot); }
        } return Integer.parseInt(version);
    }

    /**
     * Generates a UUID from the given string
     * @param str input string
     * @return generated UUID from string
     */
    public static UUID getUUIDFromString(String str) {
        return UUID.nameUUIDFromBytes(str.getBytes());
    }

    /**
     * Queries the currently running Java Virtual Machine binary path
     * @return the binary path of the JVM
     */
    public static String getJavaVM() {
        // Method 1 :: System.getProperty("java.home")
        String javaPath = System.getProperty("java.home");
        if (javaPath != null)
            return '"' + javaPath + File.separatorChar + "bin" + File.separatorChar + (System.console() != null ? "java.exe" : "javaw.exe") + '"';

        // Method 2 :: %JAVA_HOME%
        javaPath = System.getenv("JAVA_HOME");
        if (javaPath != null)
            return '"' + javaPath + File.separatorChar + "bin" + File.separatorChar + (System.console() != null ? "java.exe" : "javaw.exe") + '"';

        // Method 3 :: arguments?
        Optional<String[]> args = ProcessHandle.current().info().arguments();
        if (args.isPresent()) {
            javaPath = args.get()[0];
            return javaPath;
        }

        // no JVM can be found. how did this run anyway?
        throw new NullPointerException("what kind of JVM is this?");
    }
}
